spirit-island/spirit-island-mod

global-script.lua
Fixes bug introduced in PR #14
=> Fix minor power cards discarding to major power zone

global-script.lua
Based on #12.
This isn't particularly discoverable, but I'm not sure how best to show the alternative.
=> Add ability to draw 6 minors or 2 majors by right clicking on the power draw buttons.

global-script.lua
This is based on #5 since it uses the relative positioning.
These names are taken from the list at https://imgur.com/a/m5F5Ejg
=> Add Coastline, Top to top and Fragment 2 board layouts. 

global-script.lua
You can run via `lua GenerateMapData()` in the console, and it will generate a new notebook page with code you can copy.
=> Add a helper function that allows easier generation of board layout config.

.luacheckrc, global-script.lua, objects/1ea4cf/script.lua, objects/3f3e22/contained/4a3136/script.lua, objects/3f3e22/contained/8616a2/script.lua, objects/3f3e22/contained/a9a196/script.lua, objects/4a3136/script.lua, objects/5a95bc/script.lua, objects/8616a2/script.lua, objects/a9a196/script.lua, objects/dd3d47/script.lua, objects/e8f3e3/script.lua
=> Cleanup uses of unknown variables

.luacheckrc, global-script.lua, objects/029995/script.lua, objects/1d9bcd/script.lua, objects/1ea4cf/script.lua, objects/255ab0/contained/67e1bf/script.lua, objects/277a4f/script.lua, objects/3f3e22/contained/4a3136/script.lua, objects/3f3e22/contained/8616a2/script.lua, objects/3f3e22/contained/a9a196/script.lua, objects/3f3e22/script.lua, objects/47e3ef/contained/bddbfb/script.lua, objects/4d3c15/script.lua, objects/613ea4/script.lua, objects/9ad187/script.lua, objects/9f84fc/script.lua, objects/a245f8/script.lua, objects/a62bd7/contained/15836a/script.lua, objects/a62bd7/contained/24908a/script.lua, objects/a62bd7/contained/3b674d/script.lua, objects/a62bd7/contained/942899/script.lua, objects/a62bd7/contained/aeb4fa/script.lua, objects/a62bd7/contained/bf89e8/script.lua, objects/a62bd7/contained/cb7231/script.lua, objects/a62bd7/contained/fabcad/script.lua, objects/a9a196/script.lua, objects/b765cf/script.lua, objects/bee103/script.lua, objects/c16363/contained/eb0571/script.lua, objects/e8f3e3/script.lua
=> Add `local` to a bunch of variables. 

script.lua
There is no reason to limit the UI to the players or spirits currently in the game.
=> Show UI for all possible players.

CUSTOM.md
Writing up a guide for how to make sure that custom content is fully compatible with the mod
=> Adding custom content guide

script.lua
This updates the global (side) and unseated swap places buttons.
=> Don't show swap buttons for Black/Grey.

objects/125e82/object.json, objects/2ca216/object.json, objects/33c4af/object.json, objects/794c81/object.json, objects/901e41/object.json, objects/c99d4d/object.json, objects/d3dd7e/object.json, objects/d7d593/object.json, objects/dce473/object.json, objects/e267b0/object.json, objects/fe680a/object.json
Chry's site has gone down, so obtaining it from there isn't working anymore.
=> Switch Chry's hardwood table asset to hosting on steamusercontent.

CUSTOM.md, objects/1b39da/object.json, objects/1b39da/script.lua, objects/BnCBag/contained/788333/contained/495c9a/object.json, objects/BnCBag/contained/788333/contained/495c9a/script.lua, savegame.json, script-state.json, script.lua
To help with implementing Dances Up Earthquakes.
=> Add a hook for gaining and paying energy.

script.lua
I messed up when I wrote the energy hook code; just fixing that here. Thanks to Lolzax for pointing it out.
=> Fix a typo in the arguments to onGainPay().

objects/1ea4cf/script.lua, objects/efad15/contained/9ad187/script.lua, script.lua
In case the Endless Dark is left in the player area.
As per the discussion in #126, it seems this is a possibility that wants to be accounted for.
=> Count presence in player areas for presence loss and Deep Slumber.

objects/1ea4cf/script.lua
For Unconstrained Fangs' prepared beasts.
=> Ignore beasts in player areas for Russia's loss condition.

CUSTOM.md, objects/0e627b/contained/fddf31/script.lua, savegame.json, script.lua
To aid in implementing Mentor.
=> Add a hook to modify the number of cards gained.

objects/aidBoard/script.lua
=> Fix a bug when exploring with an empty deck and locked card.

script.lua
Implementing Destiny Unfolds requires hidden information, and thus hiding zones. These hiding zones should update with colour and place swaps.
=> Make swapping colours and places adjust hiding zones.

script.lua
=> Add a hotkey to spawn reminder tokens.

objects/1ea4cf/script.lua
We discussed this in https://github.com/spirit-island/spirit-island-mod/pull/126#issuecomment-1754321282, and then I totally forgot to do it.
=> Handle destroyed beast Incarna for Russia's loss condition.

objects/0b39ea/script.lua
It would add the city and disease to every land with towns, not just the highest.
=> Fix a bug with HME 2 setup on thematic boards.

objects/45e367/contained/09004a/script.lua
Like what we had in the additive mod (though now with a slightly nicer implementation). Hopefully this'll clear up the confusion Rei was having, and other people in the Discord seemed to like the idea too.
=> Have Dark Fire combine its Moon and Fire element bags.

objects/91570e/object.json
Updated Larger Surges (Scenario) face image (missing setup and typo).
=> Larger Surges Image
