global-script.lua

- Fix indenting.
- Use `local`.
- Return boolean directly.

Cleanup tCompare.

---

global-script.lua

Tabletop simulator doesn't like players changing colors more than once a frame, and the old code changed the wrong player to boot.  To fix this, when swapping two player colors (which requires 3 color changes):
- Wait 1 frame for the second color change
- Wait 2 frames (one more frame) for the second color change.
Also skip updating the player area if no players or spectators are present, which hopefully should reduce some error spam when leaving games.

Fix colorswapping with existing players.

---

.luacheckrc
global-script.lua
objects/dae0de/script.lua

This also sorts the list of globals in the luacheck config.

Remove uses of `broadcastToColor` in favor of `Player[color].broadcast`.

---

script.lua

If no states are locked, the token is removed
This is #26 rebased on the rewritten commits.

Set defence tokens to the highest state that is locked.

---

objects/SetupChecker/script.lua

Currently, the adversary/scenario pnael is still shown on load.

Close all setup panels on load, if the game is started.

---

objects/013dfc/object.json
objects/72de5c/object.json
objects/SetupChecker/script.lua
objects/a576cc/object.json
objects/b35fd5/object.json
objects/bd2a4a/object.json

This matches the names used in the community challenge spreadsheet, and for the
ones I could find in the rules books the capitalization there.
This also changes the pick spirit code to be case insensitive.

Adjust capitalization of spirit names.

---

script.lua

Tables are compared by identity, so comparing to `{}` for equality is always going to be false.

Handle passing `nil` to `types` in `upCastPosSizRot` correctly.

---

script.lua

I ran into issue with player bag having extra objects due to having #57 applied
locally. This add a bit of defensive programming to handle unexpected objects
in the player bags.

Make color swap code more resilient to unknown items in player bags.

---

TIPS.md

These tips are not meant to be read in the GitHub repository but I'm not familiar enough with TTS modding to add code to display them in game.
But I imagine that the basic instructions for play would be shown as part of the game setup UI, and also be available near the rule-book area (where they would be combined with the intermediate and advanced tips). Possibly collapsible/toggleable text would be used to toggle the visibility of the intermediate and advanced tips.
More tips are welcome, these are just the ones that I could think of initially.

Add tips for players, especially first-time players

---

script.lua

It was reported that the turn order UI text could get mangled, replacing
"Fast Power Phase" with "st Power Pha". I suspect this is because the code
to remove >> << from around the phase was being run twice, removing two more
characters from each end. Changing it to find-and-replace the >> << out
should make it robust against this.

Adjust the code that updates the turn order UI to be more robust.

---

objects/SetupChecker/script-state.json
objects/SetupChecker/script.lua
objects/SetupChecker/ui.xml
script.lua

It ensures a game which is as close to the top of the selected difficulty range as possible, given the selected adversary/adversaries.
Conveniently, if this is selected with a single random adversary and the default 0-11 difficulty range, it emulates the much-requested "random level 6 adversary".

Add the "maximise adversary level" setup option.

---

objects/SetupChecker/script.lua
script.lua

The motivation for making this change is that spectators appear to be able to interact with Custom UI, but not Classic UI. This means that the "Play Spirit" button didn't work if you opened a saved game in single player and instead needed to use the builtin color picker.
Since the Custom UI allows controlling visibility per-player, I took advantage of that to not show the UI for yourself, and not show the swap places/colors buttons for spectators.

Use Custom UI (instead of Classic UI) for swapping between spirits.

---

script.lua

Since #100, `updateSwapButtons` just calls `setupSwapButtons` on each table, so we can just call `updateColorPickButtons` in `setupTableButtons`, since the only difference is the former respects `showPlayerButtons`.

Hide color pick buttons when loading an in progress game.

---

objects/SetupChecker/ui.xml

Also, this adjusts the heights to reflect how much space is available before running into an obstacle, and adjust the widths to match the actual width of the contents.
While working on switching the gain a spirit functionality to use custom UI instead of classical, I wanted to temporarily add a button to gain a spirit near the player area. It took me a bunch of trial and error to figure out what position to use, since the position and heights of the panels had only a vague relation to where the visible bits of the panel were. This is because the panels were positioned by their centers, but their height was up to about 3 times that of the contents, which resulted in the specified position being somewhat below the visible contents.
This shouldn't affect that actual size or position of …

Adjust SetupChecker panels to use the upper left corner as the point where they are positioned from.

---

script.lua

This allows for aspects with bonus element spaces, *à la* Warrior Thunderspeaker.
While this is adding pre-emptive supporting infrastructure for Nature Incarnate content, it's part of content we've seen through an official announcement (Warrior Thunderspeaker was shown to have at least one bonus track space with an element on it), and is something quite likely to be mirrored on player-made aspects, so hopefully it meets the criteria for pre-emptive inclusion.

Count elements on aspects in the play area regardless of position and lock status.

---

objects/JEBag/contained/299e38/contained/86c840/script.lua
objects/aidBoard/script.lua
script.lua

The aidBoard getStage() function, when taking a substring of an invader card's lua script in order to find that invader card's stage, would take the entire script from the end of "cardInvaderStage=" to the end of the script. This required the definition of cardInvaderStage to be the final line of the script in order to work properly, and thus could break on custom adversaries with custom invader cards that include extra scripting. This is easily fixed by only taking one character (stage numbers are always one digit), instead of all characters to the end of the script.

Fix a potential bug with custom adversaries and the invader board UI.

---

CUSTOM.md
objects/0e627b/contained/fddf31/script.lua
objects/1a3d98/contained/241617/script.lua
objects/SourceSpirit/script.lua
objects/adffc0/contained/38188e/script.lua
objects/efad15/contained/9ad187/script.lua
objects/f33e62/contained/d440a5/script.lua
objects/f9ea89/contained/bec5da/script.lua
script.lua

Namely, Days That Never Were, Deep Slumber, Sunshine, and Immense. If the object was moved to the wrong spirit's play area first, it would broadcast the message that it was the wrong spirit, but the object would still have its setupComplete variable marked as true. as such, explicitly set setupComplete to false if setup fails due to being in the wrong spirit's area.

Fix a bug where spirit-specific setup items didn't work if moved to the wrong spirit first.

---

objects/SetupChecker/script-state.json
objects/SetupChecker/script.lua
objects/SetupChecker/ui.xml
objects/e924fe/script.lua
script.lua

Some people on the Discord asked for this, and iakona indicated he might be interested in adding it at some point, so I coded it up. Two things to note:
- I've hard-coded all the possible layouts for each player count. It doesn't suffice to simply select a random set of boards, as that may give non-contiguous islands (and the oceans aren't lined up properly for archipelago). A "proper" solution to ensuring the set of boards remain contiguous would still need a hard-coded network of adjacencies, and then would need to do some sort of algorithm to ensure the set was contiguous (e.g. flood fill to determine whether it's contiguous and reroll if not, or something else to build a continuous set). That'd be a fair bit of extra code to maintain, and the set of possibilities was small enough to …

Add a variant option to randomly permute the thematic boards used.

---

objects/adffc0/contained/38188e/script.lua
objects/efad15/contained/9ad187/script.lua
objects/f33e62/contained/d440a5/script.lua
script.lua

Fix #113.
This could occur if the objects were picked up a moved within the player area. This was because the setupComplete variable was stored in a way that did not persist across save/reload. Store it in script state instead to fix that. This also require slight changes to Deep Slumber, Pour Down Power Across the Island, and Ocean's Drowning bag, to prevent their onSave() functions overwriting the script state.

Fix a bug where objects' doSetup() functions could be called again after save/reload.

---

objects/37a592/script.lua

Currently, Russia and Prussia's invader deck setup treat specially placed stage 2 cards (e.g. "C") as stage two cards, but Scotland's doesn't. As Scotland is currently the only specially placed stage two card, it never has to deal with itself, so it's okay. But with HME coming, this will be necessary.

Have Scotland's InvaderDeckSetup() respect special stage 2 cards.

---

objects/SetupChecker/script.lua

Primarily the race condition that would prevent all the relevant dropdowns getting updated if an adversary and a scenario were both loaded in simultaneously, but I fixed a few other bugs I noticed while I was at it.
Also make newly added expansions default to being enabled.

Fix bugs around updating the SetupChecker UI.

---

savegame.json
script.lua

Fix #119.
One solution to this would have been to rename spirit markers to something like "Red's Sun-Bright Whirlwind Marker", but I didn't really like the idea of doing that. Instead, I've given all spirit markers are "Spirit Marker" tag, and then I'm recolouring by directly comparing tint values.
TTS has a built-in overload of == for comparing colour objects, with a default floating point tolerance of 0.01, so this is fairly safe. However, it does mean that if people manually retint their spirit markers, they won't then be altered by swapping colours. It could be argued this is desirable behaviour, however.

Recolour spirit markers when swapping colours. 

---

objects/1ea4cf/script.lua
objects/efad15/contained/9ad187/script.lua
savegame.json
script.lua

For example, the Endless Dark. This will ensure they interact correctly with the presence loss condition and Serpent's Deep Slumber.

Add the Island Tile tag to allow non-board parts of the island.

---

objects/JEBag/contained/80b54a/contained/c578b2/script.lua

They are all zero, but not setting them means it doesn't get the Blitz discount.

Set the cost and elements on Nature's Connection.

---

script.lua

Before spirit markers were automated, the global "Grab Spirit Markers" option wouldn't grab markers for those who already had them. Revert to that behaviour.
It's common in public lobbies for some players to pick their spirits, grab spirit markers, and use the spirit markers to begin putting dibs on boards. When the remaining players pick spirits, they then want to grab spirit markers. They could right-click their spirit panels specifically, but often use (or want to use) the global option, which creates duplicate markers for those who already have them.

Make grabSpiritMarkers() skip extant markers.

---

objects/84e8f2/contained/96f27d/contained/a27e7b/script.lua
objects/BnCBag/contained/05f7b7/contained/40a9cb/script.lua
objects/BnCBag/contained/cfd4d1/object.json
objects/BnCBag/contained/cfd4d1/script.lua
objects/JEBag/contained/299e38/contained/6d14c5/script.lua
objects/JEBag/contained/299e38/contained/86c840/script.lua
objects/JEBag/contained/299e38/contained/b7ac93/script.lua
objects/JEBag/contained/299e38/contained/c5a72e/script.lua
objects/JEBag/contained/98a916/contained/bab312/script.lua
objects/JEBag/contained/98a916/contained/d45b0d/script.lua
script.lua

E.g. "Grab Reminder" or "Return Fear" buttons. They were wiping all buttons from the cards, with `clearButtons()`, which could interfere with some custom scripting.
To explain the rationale for this change, Lolzax is working on some scripting for impending cards that adds additional buttons to impending power cards (changing the amount of energy they were impended with, or designating them as targets for G3). But the "Grab Reminder" buttons on Dream of the Untouched Land and Bargains of Power and Protection wipe *all* buttons from the card when they're pressed, including any extra ones for impending.

Make buttons on power/event/fear cards remove only themselves.

---

script.lua

2d72935390009e035f9d9508bbb8810786bf04e1 completely broke gaining powers when playtest powers were disabled. *Mea culpa*.

Fix a bug when gaining powers without playtest powers.

---

script.lua

Fix #138, fix #140 and fix #141. Also allow supplementing from the normal deck when the playtest deck + discard is empty, or vice versa.

Fix a variety of bugs when reshuffling decks on power gain.

---

CUSTOM.md
objects/aidBoard/script.lua
savegame.json
script.lua

To aid in implementing Dark Fire.

Add hooks for modifying elements and thresholds.

---

script.lua

Changing the colour of a hand requires destructing and respawning it. Previously, the new hand was being spawned one line of code before the old hand was destructed. As such, the GUID of the hand was still occupied by the old copy of the hand. Swapping these lines, to destruct the old hand before spawning the new, allows the new hand to use the GUID of the old hand, preserving GUID.
The changing GUIDs don't cause any problems in the current mod, as hands are always accessed by index rather than GUID. However, this is an issue I ran into when writing stuff for the NI. I could get around the changing GUIDs, but it's such a simple fix, with no side-effects as far as I can tell, that I figure it may as well be changed here.

Preserve hand GUIDs when swapping colours.

---

script.lua

Fix #150.
This has it discard powers when gaining powers from in front of another spirit, as I argued for in #150, but I can change that to just fix the unintentional discards if you disagree with me.

Fix discarding the wrong player's powers when picking.

---

objects/aidBoard/script.lua
script.lua

aidBoard's playerReadyGuids table didn't *just* store GUIDs, but the Global code also maintained a set of associated colours in there. This is a bad violation of encapsulation, and it's very difficult to tell, just reading the aidBoard code, where all the stored colours come from. Fix this by having Global never touch playerReadyGuids, and having aidBoard derive the required information directly from Global's seatTables variable. In doing so, fix #154, as information is no longer stored in playerReadyGuids that will be lost on save and reload.

Refactor ready helper code to improve encapsulation.

---

script.lua

That is, when using "maximise adversary level" with random double adversaries, prefer combinations like 4/4 to 6/0.
As it stands, the "maximise adversary level" option is pretty useless with random double adversaries. It maximises the level of the leading adversary first, then the level of the supporting adversary given that. As such, it almost always produces combinations with the supporting adversary at level 0 or level 1 (unless you pump the difficulty level up above what single adversaries can provide). In my experience, this isn't what people are playing double adversaries looking for. A 6/0 game is practically the same as a single adversary game, while something like a 4/4 game is a much more interesting combination (that often shakes out around the same difficulty).
With this …

Make random doubles tend to equal levels when maxed.

---

script.lua

Someone reported a bug that the power cards they gained were appearing face down. They had the deck face-up, and dealing flips the cards. They shouldn't really have the deck face-up, but it seems no trouble to explicitly set the rotation when dealing cards, rather than simply flipping them.

Set rotation explicitly when dealing cards.

---

script.lua

Mainly for the benefit of Infestation of Venomous Spiders, but also for repeated powers such as Portents of Disaster or Blinding Glare, and possibly for Rain and Mud, etc.
Normally when I use Infestation of Venomous Spiders, I've been stacking up several reminder tokens in the land, removing them one at a time as I skip actions there. And yesterday I had a Relentless Gaze game where I was using Portents of Disaster several times in one land, and had to put multiple tokens there to remember how much fear to generate when I finally killed something there. So I thought I'd add numbers to the reminder tokens to keep track of these things.

Add the ability to display numbers on reminder tokens.

---

objects/BnCBag/contained/c25a68/object.json
objects/JEBag/contained/98a916/contained/f0e64c/object.json
objects/JEBag/contained/98a916/object.json

To, respectively:
- Remove the "Dahan cannot Move out of target land" line that was on the version of Bog previewed in the Backerkit but not in the version printed in NI, and
- Include the "from any spirit" note for the presence gather on the version of Void that was printed with NI.

Update the images for Roiling Bog and Consuming Void.

---

objects/c4e8cd/script.lua
script.lua

I had to refactor some of the global card-dealing code, so that I wouldn't have to duplicate all of it in Destiny Unfolds.

Add scripting for Destiny Unfolds

---

objects/Editors/contained/02413e/script.lua
objects/Editors/contained/9207a4/script.lua
objects/Editors/contained/d667fe/object.json

- Fixed just-imported cards running into errors when updating their Reminder or Thresholds. 
- Update buttons now refer to unnamed cards or spirits as 'an unnamed Power Card or Spirit' when broadcasting. 
- Populate buttons on the Spirit Editor now remind the player to flip the Spirit Panel over if needed.

Power/Spirit Editor Fixes
